### ISSUE TITLE
2장: 시퀀스 빌더는 왜 존재할까?

### ISSUE THREAD

**Issue by chaeniiz** [graebbu/damn-easy#2]
무엇을 위한 빌드업일까?

**Comment by chaeniiz** [comment]
코루틴 스코프와 비슷한 형태의 개념을 차용함. 시퀀스 빌더로 쉽게 이해시켜 주려고 했는데 시퀀스 빌더를 몰라서 어리둥절해진 상황. ㅎ

**Comment by hjiee** [comment]
굿
